### ISSUE TITLE
depot_url is not respected

### ISSUE THREAD

**Issue by jkerry** [test-kitchen/kitchen-habitat#18]
Setting a value for depot_url is ignored by the hab CLI. It's not clear if this is because the env var the provisioner sets is not respected by the CLI or the provisioner is not setting the value in the right execution context.

```yaml
driver:
  name: docker

provisioner:
  name: habitat
  depot_url: https://totally.obviously.fake.com

platforms:
  - name: centos-7.4

suites:
  - name: postgresql
    provisioner:
      package_origin: core
      package_name: postgresql
    driver:
      instance_name: postgresql
      forward:
        - 5432:5432
```

This configuration, for example, successfully converges while pulling packages from the default depot.
