### ISSUE TITLE
Support multiple converges

### ISSUE THREAD

**Issue by jvogt** [test-kitchen/kitchen-habitat#33]
A second converge results in an error from the supervisor that the service is already loaded.  I think this could be resolved either through:

a) Adding `--strategy at-once` to the hab svc load command, and skipping it on subsequent runs, or
b) Unloading the service if its running, installing the new pkg, and then loading the service again.

Thoughts?

Repro steps:

```
---
driver:
  name: vagrant

provisioner:
  name: habitat
  install_latest_artifact: true
  package_origin: jvogt
  package_name: habichefdemo

platforms:
  - name: centos-7

suites:
  - name: default-habitat
```

1) `hab pkg build`
2) `kitchen converge`
3) `hab pkg build`
4) `kitchen converge`

```
...
      ✗✗✗
       ✗✗✗ [Err: 3] Service already loaded, unload 'jvogt/habichefdemo/0.1.0/20190118055505' and try again
       ✗✗✗
...
```
