### ISSUE TITLE
How to build and test a local package

### ISSUE THREAD

**Issue by mhedgpeth** [test-kitchen/kitchen-habitat#5]
I would like to use kitchen to test and build a local package with docker as the provisioner and inspec as the verifier. I have a structure similar to the one in the tutorial: https://github.com/habitat-sh/habitat-example-plans. I _think_ I would like to put a `.kitchen.yml` inside of the `habitat` folder there.

**Comment by bdangit** [comment]
You should be able to use the following `.kitchen.yml` to do just that:


```
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: habitat
  package_origin: core
  package_name: redis

verifier:
  name: inspec

platforms:
  - name: ubuntu-15.10

suites:
  - name: default
```
